import Head from "next/head";
import Image from "next/image";
import TableGrid from "../src/components/TableGrid";
import TopBar from "../src/components/TopBar";
import styles from "../styles/Home.module.css";
import { useState } from "react";

function Home() {
  const [seq1, setSeq1] = useState<string>("TCCAGAGATCCATC");
  const [seq2, setSeq2] = useState<string>("TCAGAGATCAAAATC");
  const [mode, setMode] = useState<"global" | "local">("global");
  const handleSend = (
    input1: string,
    input2: string,
    mode: "global" | "local"
  ) => {
    setSeq1(input1);
    setSeq2(input2);
    setMode(mode);
    // Perform the necessary actions with input1, input2, and mode
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Local Alignment</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <TopBar onSend={handleSend} />
        <h1>Next.js Local Alignment</h1>
        <TableGrid seq1={seq1} seq2={seq2} />
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}

export default Home;
